### ISSUE TITLE
Error handling not yet good enough

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/spectrum#24]
**Describe the bug**

```
Traceback (most recent call last):
  File "cryptoadvance/specterext/spectrum/bridge_rpc.py", line 86, in multi
  File "cryptoadvance/specterext/spectrum/bridge_rpc.py", line 86, in <listcomp>
  File "cryptoadvance/spectrum/spectrum.py", line 348, in jsonrpc
  File "cryptoadvance/spectrum/spectrum.py", line 343, in jsonrpc
  File "cryptoadvance/spectrum/spectrum.py", line 57, in wrapper
  File "cryptoadvance/spectrum/spectrum.py", line 1025, in walletcreatefundedpsbt
cryptoadvance.spectrum.spectrum.RPCError: ('Insufficient funds', -4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask/app.py", line 1523, in full_dispatch_request
  File "flask/app.py", line 1509, in dispatch_request
  File "flask_login/utils.py", line 272, in decorated_view
  File "cryptoadvance/specter/server_endpoints/wallets/wallets.py", line 531, in send_new
  File "cryptoadvance/specter/commands/psbt_creator.py", line 115, in create_psbt
  File "cryptoadvance/specter/wallet.py", line 1714, in createpsbt
  File "cryptoadvance/specter/rpc.py", line 459, in fn
  File "cryptoadvance/specterext/spectrum/bridge_rpc.py", line 98, in multi
AttributeError: 'object' object has no attribute 'status_code'
```
**To Reproduce**
1. Create a PSBT with a VERY low fee
2. Sign PSBT
3. Send Transaction

**Expected behavior**
The error message needs to bubble up in the UI to the user

**Desktop (please complete the following information):**
 - v1.14.0-pre5

**Comment by k9ert** [comment]
Now, good enough. The #2055 is green and will soon be merged.
