### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/spectrum#5]
```
spectrum
[2022-07-14 09:37:21,427] INFO in spectrum: RPC called getbalances wallet_name: specterbd9330750bc34d3b/myhot
spectrum
[2022-07-14 09:37:21,435] ERROR in spectrum: FAIL method getbalances wallet specterbd9330750bc34d3b/myhot exc unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
spectrum
Traceback (most recent call last):
spectrum
File "/usr/src/app/src/cryptoadvance/spectrum/spectrum.py", line 323, in jsonrpc
spectrum
res = m(wallet, *args, **kwargs)
spectrum
File "/usr/src/app/src/cryptoadvance/spectrum/spectrum.py", line 57, in wrapper
spectrum
return f(*args, **kwargs)
spectrum
File "/usr/src/app/src/cryptoadvance/spectrum/spectrum.py", line 760, in getbalances
spectrum
"trusted": round(confirmed * 1e-8, 8),
spectrum
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
spectrum
[2022-07-14 09:37:21,441] INFO in _internal: 10.244.0.122 - - [14/Jul/2022 09:37:21] "POST /wallet/specterbd9330750bc34d3b/myhot HTTP/1.1" 200 -
spectrum
[2022-07-14 09:37:28,839] INFO in healthz: ready?

```

**Comment by k9ert** [comment]
Solved via changing everything to decimal.
